### PR TITLE
Ftl php benchmark

### PR DESCRIPTION
**Pull request by priyawadhwa**

### CODE REVIEW

**Comment by dlorenc** [comment]
```
Step #2 - "build-image-gcr.io/ftl-node-test/packages_test-image:latest":   Failed to clone https://github.com/silexphp/Pimple.git, git was not found, check that it is installed and in your PATH env.  
```

**Comment by priyawadhwa** [comment]
Hmm so not sure why it failed initially, but I ran kokoro again and it passed

**Comment by aaron-prindle** [comment]
Also we should probably make some benchmark libs as each runtime is going to have duped code.

**Comment by priyawadhwa** [comment]
I got the small/medium/large apps by running the same queries on bigquery and taking the 20th, 50th and 95th percentiles in terms of number of required dependencies.

Definitely think a benchmark lib would be good!

**Pull request merged**
