### PR TITLE
Use mktemp instead of shuf.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
cc @nkubala

**Comment by nkubala** [comment]
nice :+1:

**Comment by dlorenc** [comment]
Actually to use this in OSX the tempdir needs to be in $HOME. What do you think of using a fixed config dir?

**Comment by nkubala** [comment]
that should be fine. really the only concern is that the directory doesn't already exist for some reason so we can safely delete it when the tests are done.

**Comment by dlorenc** [comment]
Could you expand on that a bit? I'm not sure I understand the concern.

**Comment by nkubala** [comment]
sure. since this is a temp directory that should be deleted when the script is done running, I just wanted to make sure the name of the new directory wasn't a directory that already existed on the filesystem. if it was, it would end up deleting something that it didn't have ownership of.

for example, if there's already a directory called `/tmp/configs`, and some other process is using it, then if the script decides to create `/tmp/configs` and put the test configs in it, and then delete it at the end, problems could happen.

with what you have right now, we're assuming there isn't already an existing `/.cfg` directory in the directory that this script is being run, but I think that's probably fine.

**Pull request merged**
