### PR TITLE
added support for local cloudbuild by making waitFor array

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
seems waitFor doesn't work properly in container-builder-local, was getting:
2017/11/22 15:01:00 Error loading config file: repeated string fields containing one element must be spe
cified like ['foo'], not 'foo'

**Comment by dlorenc** [comment]
I think you might just have to put the 'waitFor': value in a list, something like: waitFor: ['x'] instead of waitFor: 'x'

**Comment by aaron-prindle** [comment]
It's working with just changing waitFor to be an array, updated PR

**Comment by aaron-prindle** [comment]
passing in Kokoro, Travis still hasn't started.  Merging

**Pull request merged**
