### PR TITLE
Add a script for checking if there are any security patches available…

### PR DESCRIPTION
**Pull request by dlorenc**
… for an image.

cc @nkubala @sharifelgamal 

Usage:
```shell
$ python main.py gcr.io/google-appengine/debian
INFO:root:Found 10 unpatched vulnerabilities in gcr.io/google-appengine/debian
```

There's a bug for debian8 right now, but it's getting fixed in gcloud.

### CODE REVIEW

**Comment by nkubala** [comment]
would it be worth adding an option that returns the actual information for each unpatched vulnerability? or is this script just going to be used as a precheck for running another patch script or something

**Comment by sharifelgamal** [comment]
What's the bug in debian8?

**Comment by dlorenc** [comment]
> What's the bug in debian8?

Sorry, the bug isn't in debian8, it's in gcloud. gcloud errors when running the describe command on debian8. @tejal29 is fixing that now.



> would it be worth adding an option that returns the actual information for each unpatched vulnerability? or is this script just going to be used as a precheck for running another patch script or something

I added a command to the output so you can figure out the full list. The command is pretty verbose so I don't want to inline the output here.

**Comment by nkubala** [comment]
> I added a command to the output so you can figure out the full list. The command is pretty verbose so I don't want to inline the output here.

ah cool, I missed that. :+1:

**Pull request merged**
