### PR TITLE
revert cloudbuild rule change for ftl integration test

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Original PR had incorrect rule, node_builder_image.tar instead of node_builder_image
Still seeing errors using 'bazel run' with correct rule though as the main.py entrypoint errors w/o args.  Reverting for now to get tests passing, viable workarounds include:
- [ ] a main.py flag for a passthrough to just load the docker image
- [ ] ignoring the bazel run error in cloudbuild

**Comment by aaron-prindle** [comment]
travis taking a very long time to startup

**Comment by dlorenc** [comment]
As long as kokoro passed you should be good.

**Comment by aaron-prindle** [comment]
Can't merge it seems as travis is 'REQUIRED'

**Pull request merged**
