### PR TITLE
kokoro presubmit for ftl integration test

### PR DESCRIPTION
**Pull request by priyawadhwa**

### CODE REVIEW

**Comment by dlorenc** [comment]
Looks like you need a shellcheck disable.

**Comment by dlorenc** [comment]
Nice! although it doesn't look like kokoro actually ran..

**Comment by priyawadhwa** [comment]
Yah, I think the CL has to go through first and then hopefully it'll work!

**Comment by priyawadhwa** [comment]
kokoro:run

**Comment by dlorenc** [comment]
Looks like the kokoro service account is missing permissions to push to ftl-node-test.

**Pull request merged**
