### PR TITLE
Stop using interruptingcow, just checks the first page

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by nkubala** [comment]
since the entry we're looking for should be the most recent one, is just checking the first page not sufficient? was this not working before?

**Comment by tmatsuo** [comment]
@nkubala 

The test passes locally for my project.

1. interruptingcow causes occasional uncaught exception.
2. We have filters specific enough, so it is ok with only checking the first page.

**Comment by tmatsuo** [comment]
@nkubala 

Yes, checking the first page is sufficient.

The way it was implemented before is that it uses the entire iterator from the `list_entries`, which is bad because the iterator won't stop until the server scan all of the possible logs.

On the other hand, explicitly using the first page works because the library returns an empty page if the server response doesn't have any entries.

**Comment by tmatsuo** [comment]
@nkubala CS fix done, PTAl

**Pull request merged**
